server:
  port: 8081
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: foo=bar, baz
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-path: /health
        health-check-timeout: 30s
  application:
    name: charl-common
#    rabbitmq
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
guava:
  cache:
    properties:
      maximumSize: 2048
      maximumWeight: 1
      expireAfterAccessDuration: 10
      initialCapacity: 1024
security:
  user:
    name: user
    password: 123456