server:
  port: 8081
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: foo=bar, baz
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-path: /health
        health-check-timeout: 30s
  application:
    name: charl-common
#  zipkin:
#    base-url: http://192.168.65.128:9411/
##    取样率 100
#  sleuth:
#    sampler:
#      probability: 1.0
#rabbitmq config
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    publisher-confirms: true
#redis config
  redis:
    host: 192.168.65.128
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 100ms
        min-idle: 0
    timeout: 1000ms
#guava config
guava:
  cache:
    properties:
      maximumSize: 2048
      maximumWeight: 1
      expireAfterAccessDuration: 10
      initialCapacity: 1024
security:
  user:
    name: user
    password: 123456
charl:
  demo:
    userName: charl
    password: 123456
    url: 192.168.65.128
    port: 8083